export const ListIcon = [

    "address-book",
    "address-card",
    "ambulance",
    "bible",
    "bicycle",
    "biking",
    "birthday-cake",
    "bone",
    "bong",
    "bowling-ball",
    "briefcase",
    "briefcase-medical",
    "broadcast-tower",
    "broom",
    "brush",
    "bus-alt",
    "calculator",
    "calendar-alt",
    "camera",
    "campground",
    "candy-cane",
    "cannabis",
    "car-alt",
    "carrot",
    "cart-arrow-down",
    "cat",
    "church",
    "desktop",
    "futbol",
    "gamepad",
    "gas-pump",
    "hamburger",
    "hammer",
    "headphones",

]